FROM node:16.13.0-alpine as build
WORKDIR /usr/src/app
COPY package*.json .
RUN npm install -g @angular/cli
RUN npm install
COPY . .
RUN ng build --prod
# RUN npm run build

FROM caddy:latest
WORKDIR /etc/caddy
RUN apk update && apk add \
curl \
nano
COPY --from=build /usr/src/app/dist/NTC /usr/share/caddy
# COPY nginx.conf /etc/nginx/conf.d/default.conf

